### ISSUE TITLE
git permissions are wrong on autogen.sh shell scripts

### ISSUE THREAD

**Issue by mdaniel** [imperviousinc/beacon#5]
```
$ ./src/beacon/tools/bin/realbutil build debug
...
Traceback (most recent call last):
  File "/proj/imperviousinc/src/out/Debug/../../beacon/components/core/build_libs.py", line 186, in <module>
    sys.exit(main())
  File "/proj/imperviousinc/src/out/Debug/../../beacon/components/core/build_libs.py", line 29, in main
    run_build(args)
  File "/proj/imperviousinc/src/out/Debug/../../beacon/components/core/build_libs.py", line 178, in run_build
    build_hsk(libhsk_out, env)
  File "/proj/imperviousinc/src/out/Debug/../../beacon/components/core/build_libs.py", line 139, in build_hsk
    call(['./autogen.sh'], env)
  File "/proj/imperviousinc/src/out/Debug/../../beacon/components/core/build_libs.py", line 92, in call
    subprocess.check_call(command,env=env)
PermissionError: [Errno 13] Permission denied: './autogen.sh'
```
```console
$ git ls-tree 100.0.4896.75 third_party/hnsd/autogen.sh
100644 blob 360f7133515ec9779bcd6d93a344823d88d04d25	third_party/hnsd/autogen.sh
```
but it should be `100755` and the same for its `100644 blob 271c2ee8c33c441336395243ab53f4488af61e22	third_party/hnsd/uv/autogen.sh` friend

Or, of course, since [`build_libs.py` is yours](https://github.com/imperviousinc/beacon/blob/100.0.4896.75/components/core/build_libs.py#L139) changing it to `["bash", "autogen.sh"]` is another option

**Comment by buffrr** [comment]
Thanks!
